// admin-bash-template.js
window.AdminBashTemplates = {
    adminPanelSetup: {
        filename: 'matrix-admin-panel.sh',
        getContent: function(domain, adminUsername, adminPassword) {
            return '#!/bin/bash\n\n' +
'# Admin Panel Setup Script\n' +
'# Generated by Matrix Colony Setup\n\n' +
'set -e\n\n' +
'echo "[i] Setting up Admin Panel for domain: ' + domain + '"\n\n' +
'# Create admin-panel directory\n' +
'mkdir -p admin-panel\n\n' +
'# Create docker-compose.yaml for admin panel\n' +
'cat > ./admin-panel/docker-compose.yaml << EOF\n' +
'version: "3"\n\n' +
'services:\n' +
'  synapse-admin:\n' +
'    image: awesometechnologies/synapse-admin:latest\n' +
'    container_name: synapse-admin\n' +
'    restart: unless-stopped\n' +
'    environment:\n' +
'      MATRIX_USERNAME: "@' + adminUsername + ':' + domain + '"\n' +
'      MATRIX_PASSWORD: "' + adminPassword + '"\n' +
'      MATRIX_URL: "https://' + domain + '"\n' +
'      MATRIX_SERVER_NAME: "' + domain + '"\n' +
'    ports:\n' +
'      - "8080:80"\n' +
'EOF\n\n' +
'# Start admin panel\n' +
'docker compose -f ./admin-panel/docker-compose.yaml up -d\n\n' +
'echo "[✓] Admin Panel started successfully"\n' +
'echo "[i] Admin Panel URL: http://localhost:8080"\n' +
'echo "[i] Login with username: @' + adminUsername + ':' + domain + '"\n' +
'echo "[i] Password: ' + adminPassword + '"';
        }
    },

    createAdminUser: {
        filename: 'matrix-create-admin.sh',
        getContent: function(domain, adminUsername, adminPassword) {
            return '#!/bin/bash\n\n' +
'# Create New Admin User Script\n' +
'# Generated by Matrix Colony Setup\n\n' +
'set -e\n\n' +
'echo "[i] Creating new admin user..."\n\n' +
'# Check if synapse container is running\n' +
'if ! docker compose ps synapse | grep -q "Up"; then\n' +
'    echo "[✗] Synapse container is not running"\n' +
'    echo "[i] Please start your Matrix stack first: docker compose up -d"\n' +
'    exit 1\n' +
'fi\n\n' +
'# Create admin user using the registration script\n' +
'docker compose exec synapse register_new_matrix_user \\\n' +
'    -c /data/homeserver.yaml \\\n' +
'    -u "' + adminUsername + '" \\\n' +
'    -p "' + adminPassword + '" \\\n' +
'    -a \\\n' +
'    http://synapse:8008\n\n' +
'echo "[✓] Admin user @' + adminUsername + ':' + domain + ' created successfully"';
        }
    },

    fullAdminSetup: {
        filename: 'matrix-complete-admin.sh',
        getContent: function(domain, adminUsername, adminPassword) {
            return '#!/bin/bash\n\n' +
'# Complete Admin Setup Script\n' +
'# Combines Admin Panel and Admin User Creation\n' +
'# Generated by Matrix Colony Setup\n\n' +
'set -e\n\n' +
'echo "[i] Starting complete admin setup for domain: ' + domain + '"\n\n' +
'# Check if docker is running\n' +
'if ! docker info > /dev/null 2>&1; then\n' +
'    echo "[✗] Docker is not running. Please start Docker first."\n' +
'    exit 1\n' +
'fi\n\n' +
'# Setup Admin Panel\n' +
'echo "[i] Setting up Admin Panel..."\n' +
'mkdir -p admin-panel\n\n' +
'cat > ./admin-panel/docker-compose.yaml << EOF\n' +
'version: "3"\n\n' +
'services:\n' +
'  synapse-admin:\n' +
'    image: awesometechnologies/synapse-admin:latest\n' +
'    container_name: synapse-admin\n' +
'    restart: unless-stopped\n' +
'    environment:\n' +
'      MATRIX_USERNAME: "@' + adminUsername + ':' + domain + '"\n' +
'      MATRIX_PASSWORD: "' + adminPassword + '"\n' +
'      MATRIX_URL: "https://' + domain + '"\n' +
'      MATRIX_SERVER_NAME: "' + domain + '"\n' +
'    ports:\n' +
'      - "8080:80"\n' +
'EOF\n\n' +
'docker compose -f ./admin-panel/docker-compose.yaml up -d\n' +
'echo "[✓] Admin Panel started on port 8080"\n\n' +
'# Create Admin User in Synapse\n' +
'echo "[i] Creating admin user in Synapse..."\n' +
'sleep 5\n\n' +
'docker compose exec synapse register_new_matrix_user \\\n' +
'    -c /data/homeserver.yaml \\\n' +
'    -u "' + adminUsername + '" \\\n' +
'    -p "' + adminPassword + '" \\\n' +
'    -a \\\n' +
'    http://synapse:8008 || true\n\n' +
'echo "[✓] Complete admin setup finished!"\n' +
'echo "[i] Admin Panel: http://localhost:8080"\n' +
'echo "[i] Login with username: @' + adminUsername + ':' + domain + '"\n' +
'echo "[i] Password: ' + adminPassword + '"';
        }
    }
};

// Generator function for admin templates
window.generateAdminBashScript = function(templateName, params) {
    console.log('generateAdminBashScript called with:', templateName, params);
    
    var template = window.AdminBashTemplates[templateName];
    if (!template) {
        throw new Error('Admin template "' + templateName + '" not found');
    }
    
    var content = template.getContent(params.DOMAIN, params.ADMIN_USERNAME, params.ADMIN_PASSWORD);
    
    return {
        filename: template.filename,
        content: content
    };
};

console.log('✅ admin-bash-template.js loaded successfully');