// setup.js - Matrix Synapse Setup Script Generator
window.SetupTemplates = {
  fullSetup: {
    filename: 'matrix-synapse-setup.sh',
    getContent: function(config) {
      const {
        POSTGRES_PASSWORD,
        SERVER_DOMAIN_NAME,
        TURN_SHARED_SECRET,
        PUBLIC_IP,
        ACME_EMAIL,
        ENABLE_TURN_SERVER,
        ENABLE_LIVEKIT,
        ENABLE_ADMIN_PANEL
      } = config;

      // Escape special characters for bash
      const escapeForBash = (str) => {
        return str.replace(/'/g, "'\\''");
      };

      const escapedPostgresPassword = escapeForBash(POSTGRES_PASSWORD);
      const escapedServerDomain = escapeForBash(SERVER_DOMAIN_NAME);
      const escapedTurnSecret = escapeForBash(TURN_SHARED_SECRET);
      const escapedPublicIp = escapeForBash(PUBLIC_IP);
      const escapedAcmeEmail = escapeForBash(ACME_EMAIL);

      return `#!/bin/bash

# Matrix Synapse Complete Setup Script
# Generated by Matrix Colony Setup Wizard

set -e  # Exit on error

# ============================================
# CONFIGURATION VARIABLES
# ============================================
POSTGRES_PASSWORD='${escapedPostgresPassword}'
SERVER_DOMAIN_NAME='${escapedServerDomain}'
TURN_SHARED_SECRET='${escapedTurnSecret}'
PUBLIC_IP='${escapedPublicIp}'
ACME_EMAIL='${escapedAcmeEmail}'

# Feature flags
ENABLE_TURN_SERVER=${ENABLE_TURN_SERVER}
ENABLE_LIVEKIT=${ENABLE_LIVEKIT}
ENABLE_ADMIN_PANEL=${ENABLE_ADMIN_PANEL}

# ============================================
# FUNCTIONS
# ============================================

# Function to check and install docker
docker_installation() {
  echo "=========================================="
  echo "Step 1: Docker Installation"
  echo "=========================================="
  
  # Check if Docker is installed
  if ! docker --version >/dev/null 2>&1; then
    echo "Installing Docker..."
    sudo apt update

    sudo apt install -y ca-certificates curl gnupg

    # Add Docker’s official GPG key
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    # Add Docker repo
    echo \\
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \\
    https://download.docker.com/linux/ubuntu \\
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
      sudo tee /etc/apt/sources.list.d/docker.list >/dev/null

    # Install Docker
    sudo apt update
    sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    # enable Docker on boot
    sudo systemctl enable docker
    sudo systemctl start docker
  fi

  # Verify Docker and Docker Compose installation
  echo "Docker version:"
  docker --version
  echo "Docker Compose version:"
  docker compose version
}

# Function to create Synapse using docker compose
synapse_initialization() {
  echo "=========================================="
  echo "Step 2: Creating Synapse Docker Compose"
  echo "=========================================="
  
  # Create network if it doesn't exist
  docker network create matrix-shared 2>/dev/null || true

  # Define the YAML content for the docker-compose file
  cat <<EOF > docker-compose.yaml
version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: synapse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - matrix

  synapse:
    image: matrixdotorg/synapse:v1.147.1
    container_name: synapse
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./data:/data
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    networks:
      - matrix

  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:v0.99.19
    container_name: sliding-sync
    restart: unless-stopped
    depends_on:
      - postgres
      - synapse
    environment:
      SYNCV3_SERVER: "http://synapse:8008"
      SYNCV3_DB: "postgres://synapse:${POSTGRES_PASSWORD}@postgres/synapse?sslmode=disable"
      SYNCV3_SECRET: "b9e1af972ab2aa3463fa08e8859a7e093ee4db4a0e6093b9863c34608f3c85c2"
      SYNCV3_BINDADDR: "0.0.0.0:8009"
      SYNCV3_LOG_LEVEL: "info"
    networks:
      - matrix

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      - matrix
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    environment:
      ACME_AGREE: "true"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env

networks:
  matrix:
    external: true
    name: matrix-shared

volumes:
  caddy_data:
  caddy_config:
EOF

  echo "Synapse docker-compose.yaml created successfully!"
  docker compose up -d
  echo "Synapse services started"
}

environment_configuration() {
  echo "=========================================="
  echo "Step 3: Environment Configuration"
  echo "=========================================="
  
  cat <<EOF > .env
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
SERVER_NAME=${SERVER_DOMAIN_NAME}
SERVER_URL=https://${SERVER_DOMAIN_NAME}/
ACME_EMAIL=${ACME_EMAIL}

TURN_SHARED_SECRET="${TURN_SHARED_SECRET}"
EOF
}

caddyfile_configuration() {
  echo "=========================================="
  echo "Step 4: Caddyfile Configuration"
  echo "=========================================="
  
  cat <<EOF > Caddyfile
{
    email ${ACME_EMAIL}
}

${SERVER_DOMAIN_NAME} {
    handle /.well-known/matrix/client {
        header Content-Type "application/json"
        header Access-Control-Allow-Origin "*"
        respond \`{
            "m.homeserver": {"base_url": "https://${SERVER_DOMAIN_NAME}"},
            "org.matrix.msc4143.rtc_foci": [
                {
                    "type": "livekit",
                    "livekit_service_url": "https://rtc.${SERVER_DOMAIN_NAME}/livekit/jwt"
                }
            ]
        }\` 200
    }

    reverse_proxy /_matrix/* synapse:8008
    reverse_proxy /_synapse/* synapse:8008
    reverse_proxy /_sliding_sync/* sliding-sync:8009
    reverse_proxy synapse:8008
}

${SERVER_DOMAIN_NAME}:8448 {
    reverse_proxy /_matrix/* synapse:8008
    reverse_proxy synapse:8008
}

rtc.${SERVER_DOMAIN_NAME} {
    handle /livekit/jwt* {
        uri strip_prefix /livekit/jwt
        reverse_proxy element-call-jwt:8080
    }
    handle /livekit/sfu* {
        uri strip_prefix /livekit/sfu
        reverse_proxy livekit-server:7880
    }
}
EOF
}

homeserver_initial_configuration() {
  echo "=========================================="
  echo "Step 5: Homeserver Configuration"
  echo "=========================================="
  
  if [ -d "data" ]; then
    echo "data directory exists"
  else
    docker run -it --rm \\
    -v $(pwd)/data:/data \\
    -e SYNAPSE_SERVER_NAME=${SERVER_DOMAIN_NAME} \\
    -e SYNAPSE_REPORT_STATS=no \\
    matrixdotorg/synapse:v1.147.1 generate
  fi

  HOMESERVER_CONFIG=$(cat <<EOF
server_name: "${SERVER_DOMAIN_NAME}"
public_baseurl: "https://${SERVER_DOMAIN_NAME}/"

pid_file: /data/homeserver.pid

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [client, federation]
        compress: false

sliding_sync_proxy_url: "http://sliding-sync:8009"

# PostgreSQL 
database:
  name: psycopg2
  args:
    user: synapse
    password: ${POSTGRES_PASSWORD}
    database: synapse
    host: synapse-postgres
    port: 5432
    cp_min: 5
    cp_max: 10
  allow_unsafe_locale: true 

log_config: "/data/${SERVER_DOMAIN_NAME}.log.config"
media_store_path: /data/media_store

registration_shared_secret: "IBw6~14Q*A_PKMZ2NqU4mZolR5Np54ouvcZlhDepm4VNB#M.c:"

report_stats: false

macaroon_secret_key: "T1u#d,3=2qwUGoCN~o42PHNld3Dd0y-F5zNR~MA--Pdsgrvcf-"
form_secret: "=HNqZ*nRM25z#^V2GK8T*B3Y8dvBJQ&OqmnW*F+xaW.4RE,Phc"

signing_key_path: "/data/${SERVER_DOMAIN_NAME}.signing.key"

trusted_key_servers:
  - server_name: "matrix.org"

# User directory
user_directory:
  enabled: true
  search_all_users: true
  prefer_local_users: true

# Public rooms
public_room_list:
  enabled: true

enable_room_list_search: true
allow_public_rooms_over_federation: true

# TURN server
turn_uris:
  - "turn:${SERVER_DOMAIN_NAME}:3478?transport=udp"
  - "turn:${SERVER_DOMAIN_NAME}:3478?transport=tcp"
  - "turns:${SERVER_DOMAIN_NAME}:5349?transport=tcp"

turn_shared_secret: "${TURN_SHARED_SECRET}"
turn_user_lifetime: 86400000
turn_allow_guests: true

experimental_features:
  msc3575_enabled: true  # Sliding Sync
  msc3401_enabled: true
  msc3266_enabled: true
  msc4222_enabled: true
  msc4140_enabled: true

max_event_delay_duration: 24h

rc_message:
  per_second: 0.5
  burst_count: 30

rc_delayed_event_mgmt:
  per_second: 1
  burst_count: 20
EOF
)

  if [ -f "./data/homeserver.yaml" ]; then
    echo "$HOMESERVER_CONFIG" > "./data/homeserver.yaml"
    echo "homeserver.yaml Updated."
  elif [ -f "./data/homeserver.yml" ]; then
    echo "$HOMESERVER_CONFIG" > "./data/homeserver.yml"
    echo "homeserver.yml Updated."
  else
    echo "Creating homeserver.yaml"
    echo "$HOMESERVER_CONFIG" > "./data/homeserver.yaml" 
  fi

  docker compose restart
}

turnserver_configuration() {
  echo "=========================================="
  echo "Step 6: TURN Server Configuration"
  echo "=========================================="
  
  cat <<EOF > turnserver.conf
listening-port=3478
listening-ip=0.0.0.0

external-ip=${PUBLIC_IP}

realm=${SERVER_DOMAIN_NAME}
server-name=${SERVER_DOMAIN_NAME}

fingerprint
use-auth-secret
static-auth-secret=${TURN_SHARED_SECRET}

total-quota=100
bps-capacity=0
stale-nonce=600

no-loopback-peers
no-multicast-peers
EOF

  echo "turnserver.conf created successfully!"
}

livekit_configuration() {
  echo "=========================================="
  echo "Step 7: LiveKit Configuration"
  echo "=========================================="
  
  mkdir -p livekit

  LIVEKIT_COMPOSE=$(cat <<EOF
services:
  auth-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest
    container_name: element-call-jwt
    hostname: auth-server
    environment:
      - LIVEKIT_JWT_PORT=8080
      - LIVEKIT_URL=https://rtc.${SERVER_DOMAIN_NAME}/livekit/sfu
      - LIVEKIT_KEY=LIVEKIT_API_KEY
      - LIVEKIT_SECRET=v3ry_str0ng_and_super_l0ng_super_secret_string_here_123456789
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=${SERVER_DOMAIN_NAME}
      - HOMESERVER_URL=http://synapse:8008
    restart: unless-stopped
    ports:
      - "8070:8080"
    networks:
      - matrix

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command: --config /etc/livekit.yaml
    ports:
      - "7880:7880/tcp"
      - "7881:7881/tcp"
      - "50100-50200:50100-50200/udp"
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/livekit.yaml:ro
    networks:
      - matrix

networks:
  matrix:
    external: true
    name: matrix-shared
EOF

  LIVEKIT_CONFIG=$(cat <<EOF
port: 7880
bind_addresses:
  - "0.0.0.0"
rtc:
  tcp_port: 7881
  port_range_start: 50100
  port_range_end: 50200
  use_external_ip: true        
  node_ip: "${PUBLIC_IP}"
room:
  auto_create: true
logging:
  level: debug
keys:
  LIVEKIT_API_KEY: "v3ry_str0ng_and_super_l0ng_super_secret_string_here_123456789"
EOF

  echo "$LIVEKIT_COMPOSE" > "./livekit/docker-compose.yaml"
  echo "$LIVEKIT_CONFIG" > "./livekit/config.yaml"

  docker compose -f ./livekit/docker-compose.yaml up -d
}

admin_panel_setup() {
  echo "=========================================="
  echo "Step 8: Admin Panel Setup"
  echo "=========================================="
  
  mkdir -p admin-panel

  ADMIN_PANEL_COMPOSE=$(cat <<EOF
version: "3"

services:
  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: synapse-admin
    restart: unless-stopped
    environment:
      MATRIX_USERNAME: "@admin:${SERVER_DOMAIN_NAME}"
      MATRIX_PASSWORD: "admin12345"
      MATRIX_URL: "https://${SERVER_DOMAIN_NAME}"
      MATRIX_SERVER_NAME: "${SERVER_DOMAIN_NAME}"
    ports:
      - "8080:80"
EOF

  echo "$ADMIN_PANEL_COMPOSE" > "./admin-panel/docker-compose.yaml"

  docker compose -f ./admin-panel/docker-compose.yaml up -d
}

# ============================================
# MAIN EXECUTION
# ============================================

main() {
  echo "=========================================="
  echo "Matrix Synapse Complete Setup"
  echo "=========================================="
  echo "Starting setup at: $(date)"
  echo ""
  
  # Run Docker installation
  docker_installation
  
  # Run Synapse initialization
  synapse_initialization
  
  # Run environment configuration
  environment_configuration
  
  # Run Caddyfile configuration
  caddyfile_configuration
  
  # Run homeserver configuration
  homeserver_initial_configuration
  
  # Optional: TURN Server
  if [ "$ENABLE_TURN_SERVER" = "true" ]; then
    turnserver_configuration
  fi
  
  # Optional: LiveKit
  if [ "$ENABLE_LIVEKIT" = "true" ]; then
    livekit_configuration
  fi
  
  # Optional: Admin Panel
  if [ "$ENABLE_ADMIN_PANEL" = "true" ]; then
    admin_panel_setup
  fi
  
  echo ""
  echo "=========================================="
  echo "Setup Complete!"
  echo "=========================================="
  echo "Your Matrix Synapse server is ready!"
  echo "Domain: https://${SERVER_DOMAIN_NAME}"
  echo ""
  echo "Next steps:"
  echo "1. Register admin user: docker compose exec synapse register_new_matrix_user -c /data/homeserver.yaml http://localhost:8008"
  echo "2. Check logs: docker compose logs -f"
  echo "3. Visit your domain to verify setup"
  echo "=========================================="
}

# Run main function
main`;
    }
  }
};

// Helper function to generate and download setup script
window.generateSetupScript = function(config) {
  const template = window.SetupTemplates.fullSetup;
  if (!template) {
    throw new Error('Setup template not found');
  }
  
  return template.getContent(config);
};

// Download helper function
window.downloadSetupScript = function(config) {
  const content = window.generateSetupScript(config);
  const filename = 'matrix-synapse-setup.sh';
  
  const blob = new Blob([content], {type: 'text/plain'});
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
  
  return true;
};

console.log('✅ setup.js loaded successfully');