// bash-template.js
window.BashTemplates = {
    synapseConfig: {
        filename: 'synapse-config.sh',
        getContent: function (userSearchFlag) {
            return `#!/bin/bash

# Synapse Configuration Script
# Generated by Matrix Colony Setup

set -e  # Exit on error

# Function to print output
print_status() {
    echo "[✓] \$1"
}

print_error() {
    echo "[✗] \$1"
}

print_info() {
    echo "[i] \$1"
}

# Function to modify YAML properties
modify_yaml_property() {
    local FILE="\$1" PARENT="\$2" PROP="\$3" VAL="\$4"
    
    [ ! -f "\$FILE" ] && { print_error "File not found: \$FILE"; return 1; }
    
    print_info "Modifying \$PROP in \$FILE"
    
    # Backup
    cp "\$FILE" "\${FILE}.bak"
    
    # Escape and modify
    local ESC_PARENT=\$(printf "%s" "\$PARENT" | sed "s/[\\/&]/\\\\&/g")
    local ESC_PROP=\$(printf "%s" "\$PROP" | sed "s/[\\/&]/\\\\&/g")
    
    if command -v perl >/dev/null 2>&1; then
        perl -i -pe "BEGIN{\$in=0} if(!\$in&&/^\${ESC_PARENT}:/){\$in=1} elsif(\$in&&/^[a-zA-Z]/){\$in=0} elsif(\$in&&/^(\\s*)\${ESC_PROP}:/){\$_=\$1.\"\${ESC_PROP}: \${VAL}\\n\"}" "\$FILE"
    else
        awk -v p="\$PARENT" -v k="\$PROP" -v v="\$VAL" 'BEGIN{i=0} \$0~"^"p":"{i=1} i&&/^[a-zA-Z]/&&\$0!~"^"p":"{i=0} i&&\$0~"^[[:space:]]*"k":"{sub(k":.*",k": "v)} 1' "\${FILE}.bak" > "\$FILE"
    fi
    
    if grep -q "^[[:space:]]*\${PROP}:[[:space:]]*\${VAL}" "\$FILE"; then
        rm "\${FILE}.bak"
        print_status "Successfully updated \$PROP to: \$VAL"
        return 0
    else
        mv "\${FILE}.bak" "\$FILE"
        print_error "Failed to update \$PROP"
        return 1
    fi
}

# Function to configure user search
configure_user_search() {
    local user_search_enabled="\$1"
    local homeserver_file="./data/homeserver.yaml"
    
    if [[ "\$user_search_enabled" == "true" || "\$user_search_enabled" == "false" ]]; then
        modify_yaml_property "\$homeserver_file" "user_directory" "search_all_users" "\$user_search_enabled"
    else
        print_error "configure_user_search() argument must be true or false"
        return 1
    fi
}

# Main execution
main() {
    print_info "Starting Synapse configuration update..."
    
    # Check if homeserver.yaml exists
    if [ ! -f "./data/homeserver.yaml" ]; then
        print_error "homeserver.yaml not found at ./data/homeserver.yaml"
        print_info "Please ensure you're running this script from the correct directory"
        exit 1
    fi
    
    # Configure user search based on flag
    configure_user_search ${userSearchFlag}
    
    print_status "Configuration complete!"
    print_info "Please restart Synapse: docker compose restart synapse"
}

# Run main function
main`;
        }
    }
};

window.generateBashScript = function (templateName, params) {
    console.log('generateBashScript called with:', templateName, params);

    var template = window.BashTemplates[templateName];
    if (!template) {
        throw new Error('Template "' + templateName + '" not found');
    }

    var content;
    if (typeof template.getContent === 'function') {
        // Use the function-based template
        content = template.getContent(params.USER_SEARCH_FLAG);
    } else {
        // Use the string-based template with replacement
        content = template.content;
        for (var key in params) {
            if (params.hasOwnProperty(key)) {
                var regex = new RegExp('{{' + key + '}}', 'g');
                content = content.replace(regex, params[key]);
            }
        }
    }

    return {
        filename: template.filename,
        content: content
    };
};

console.log('✅ bash-template.js loaded successfully');
